# Generated by Django 2.2.6 on 2019-11-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestmodel',
            old_name='gender_other',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='interestmodel',
            name='bachelors_degree',
            field=models.CharField(default='Nan', max_length=250),
        ),
    ]
