# Generated by Django 2.2.6 on 2019-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_scoremodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestmodel',
            name='email',
            field=models.EmailField(default='Nan', max_length=250),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='score',
            field=models.TextField(max_length=25),
        ),
    ]
